- name: install nginx
  ansible.builtin.dnf:
    name: nginx
    state: latest

# - name: enable the service
#   ansible.builtin.service:
#     name: nginx
#     enabled: yes

# - name: starting the service
#   ansible.builtin.service:
#     name: nginx
#     state: started

# - name: copy expense.conf
#   ansible.builtin.copy:
#     src: expense.conf
#     dest: /etc/nginx/default.d/expense.conf

- name: copy expense.conf
  ansible.builtin.template:
    src: expense.conf
    dest: /etc/nginx/default.d/expense.conf

# - name: Recursively remove directory
#   ansible.builtin.file:
#     path: "{{back_folder}}"
#     state: absent

# - name: create the deleted directory
#   ansible.builtin.file:
#     path: "{{back_folder}}"
#     state: directory

# # - name: download zip folder
# #   ansible.builtin.get_url:
# #     url: https://expense-artifacts.s3.amazonaws.com/expense-frontend-v2.zip
# #     dest: /tmp/frontend.zip

# - name: Extract frontend.zip into /usr/share/nginx/html
#   ansible.builtin.unarchive:
#     src: https://expense-artifacts.s3.amazonaws.com/expense-frontend-v2.zip
#     dest: "{{back_folder}}"
#     remote_src: yes

- name: running repeatable steps
  ansible.builtin.import_role:
    name: common
    tasks_from: pre-reqs

- name: Start Nginx
  ansible.builtin.systemd_service:
    state: restarted
    name: nginx

- name: Import NewRelic Nginx Setup
  ansible.builtin.import_role:
    name: newrelic
    tasks_from: nginx