- name: Install mysql
  ansible.builtin.dnf:
    name: mysql-server
    state: latest

- name: Start service mysqld, if not started
  ansible.builtin.service:
    name: mysqld
    state: started
    enabled: yes

- name: Install Python MySQL Client
  ansible.builtin.pip:
    name:
      - PyMySQL
      - cryptography
    executable: pip3.9

# - name: Collect all info except settings and users by root
#   community.mysql.mysql_info:
#     login_user: root
#     login_password: ExpenseApp@1
#     login_host: mysql-dev.vsldo.online
#     filter: "version"
#   register: OUTPUT

# - name: print the output of previous action
#   ansible.builtin.debug: 
#     msg: "{{ OUTPUT }}"
    
- name: set mysql password
  ansible.builtin.command: mysql_secure_installation --set-root-pass ExpenseApp@1
  # when: OUTPUT.failed is true