- name: run new relic Setup
  ansible.builtin.shell: curl -Ls https://download.newrelic.com/install/newrelic-cli/scripts/install.sh | bash && sudo NEW_RELIC_API_KEY={{new_relic_nginx_key}} NEW_RELIC_ACCOUNT_ID=4425960 NEW_RELIC_REGION=US /usr/local/bin/newrelic install -n nginx-open-source-integration -y
