- name: assinging a prompt
  ansible.builtin.shell: set-prompt {{ component }}-{{ env }}


- name: installing node_exporter
  ansible.builtin.import_role:
    name: prometheus
    tasks_from: node_exporter
